export type StitchModule = 'dashboard' | 'transactions' | 'analytics' | 'split' | 'scan' | 'profile' | 'auth' | 'other';

export interface StitchScreenDefinition {
  screenKey: string;
  folderName: string;
  folderPath: string;
  module: StitchModule;
  isDark: boolean;
  hasScreenPng: boolean;
  hasCodeHtml: boolean;
}

export const STITCH_SCREENS: StitchScreenDefinition[] = [
  {
    screenKey: "ai_tavsiyeleri_dark_1",
    folderName: "ai_tavsiyeleri_(dark)_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/ai_tavsiyeleri_(dark)_1",
    module: "analytics",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: false,
  },
  {
    screenKey: "ai_tavsiyeleri_dark_2",
    folderName: "ai_tavsiyeleri_(dark)_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/ai_tavsiyeleri_(dark)_2",
    module: "analytics",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "ai_tavsiyeleri_dark_3",
    folderName: "ai_tavsiyeleri_(dark)_3",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/ai_tavsiyeleri_(dark)_3",
    module: "analytics",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "ai_tavsiyeleri_1",
    folderName: "ai_tavsiyeleri_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/ai_tavsiyeleri_1",
    module: "analytics",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: false,
  },
  {
    screenKey: "ai_tavsiyeleri_2",
    folderName: "ai_tavsiyeleri_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/ai_tavsiyeleri_2",
    module: "analytics",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "ana_ekran_dashboard_1",
    folderName: "ana_ekran_(dashboard)_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/ana_ekran_(dashboard)_1",
    module: "dashboard",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "ana_ekran_dashboard_2",
    folderName: "ana_ekran_(dashboard)_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/ana_ekran_(dashboard)_2",
    module: "dashboard",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: false,
  },
  {
    screenKey: "arkadaslarim_dark_1",
    folderName: "arkadaşlarım_(dark)_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/arkadaşlarım_(dark)_1",
    module: "split",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "arkadaslarim_dark_2",
    folderName: "arkadaşlarım_(dark)_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/arkadaşlarım_(dark)_2",
    module: "split",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: false,
  },
  {
    screenKey: "arkadaslarim_1",
    folderName: "arkadaşlarım_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/arkadaşlarım_1",
    module: "split",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "arkadaslarim_2",
    folderName: "arkadaşlarım_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/arkadaşlarım_2",
    module: "split",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: false,
  },
  {
    screenKey: "ayarlar_bildirim_baglantili",
    folderName: "ayarlar_(bildirim_bağlantılı)",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/ayarlar_(bildirim_bağlantılı)",
    module: "profile",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "ayarlar_dark_1",
    folderName: "ayarlar_(dark)_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/ayarlar_(dark)_1",
    module: "profile",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "ayarlar_dark_2",
    folderName: "ayarlar_(dark)_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/ayarlar_(dark)_2",
    module: "profile",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "ayarlar_destek_baglantili",
    folderName: "ayarlar_(destek_bağlantılı)",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/ayarlar_(destek_bağlantılı)",
    module: "profile",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "ayarlar_guncellendi_1",
    folderName: "ayarlar_(güncellendi)_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/ayarlar_(güncellendi)_1",
    module: "profile",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "ayarlar_guncellendi_2",
    folderName: "ayarlar_(güncellendi)_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/ayarlar_(güncellendi)_2",
    module: "profile",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "ayarlar_1",
    folderName: "ayarlar_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/ayarlar_1",
    module: "profile",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "ayarlar_2",
    folderName: "ayarlar_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/ayarlar_2",
    module: "profile",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "basarili_giris_yonlendirmesi",
    folderName: "başarılı_giriş_yönlendirmesi",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/başarılı_giriş_yönlendirmesi",
    module: "auth",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "bekleyen_istekler",
    folderName: "bekleyen_i̇stekler",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/bekleyen_i̇stekler",
    module: "other",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "bekleyen_istekler_dark",
    folderName: "bekleyen_i̇stekler_(dark)",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/bekleyen_i̇stekler_(dark)",
    module: "other",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "bildirim_ayarlari_dark",
    folderName: "bildirim_ayarları_(dark)",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/bildirim_ayarları_(dark)",
    module: "profile",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "borc_kapatma",
    folderName: "borç_kapatma",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/borç_kapatma",
    module: "analytics",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: false,
  },
  {
    screenKey: "borc_kapatma_dark_1",
    folderName: "borç_kapatma_(dark)_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/borç_kapatma_(dark)_1",
    module: "analytics",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "borc_kapatma_dark_2",
    folderName: "borç_kapatma_(dark)_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/borç_kapatma_(dark)_2",
    module: "analytics",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "borc_kapatma_guncel",
    folderName: "borç_kapatma_(güncel)",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/borç_kapatma_(güncel)",
    module: "analytics",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "borc_kapatma_rehberi",
    folderName: "borç_kapatma_rehberi",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/borç_kapatma_rehberi",
    module: "analytics",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "borc_kapatma_rehberi_dark_1",
    folderName: "borç_kapatma_rehberi_(dark)_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/borç_kapatma_rehberi_(dark)_1",
    module: "analytics",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "borc_kapatma_rehberi_dark_2",
    folderName: "borç_kapatma_rehberi_(dark)_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/borç_kapatma_rehberi_(dark)_2",
    module: "analytics",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "butce_asimi_bildirimi",
    folderName: "bütçe_aşımı_bildirimi",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/bütçe_aşımı_bildirimi",
    module: "analytics",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "butce_duzenleme",
    folderName: "bütçe_düzenleme",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/bütçe_düzenleme",
    module: "analytics",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "butce_planlama",
    folderName: "bütçe_planlama",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/bütçe_planlama",
    module: "analytics",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "dashboard_dark",
    folderName: "dashboard_(dark)",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/dashboard_(dark)",
    module: "dashboard",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: false,
  },
  {
    screenKey: "dashboard_koyu_mod_1",
    folderName: "dashboard_(koyu_mod)_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/dashboard_(koyu_mod)_1",
    module: "dashboard",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: false,
  },
  {
    screenKey: "dashboard_koyu_mod_2",
    folderName: "dashboard_(koyu_mod)_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/dashboard_(koyu_mod)_2",
    module: "dashboard",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: false,
  },
  {
    screenKey: "dashboard_with_budget_widget",
    folderName: "dashboard_with_budget_widget",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/dashboard_with_budget_widget",
    module: "dashboard",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "dashboard_with_interactive_budget_widget",
    folderName: "dashboard_with_interactive_budget_widget",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/dashboard_with_interactive_budget_widget",
    module: "dashboard",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "detayli_ayarlar_paneli",
    folderName: "detaylı_ayarlar_paneli",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/detaylı_ayarlar_paneli",
    module: "profile",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "fatura_tarama_dark_1",
    folderName: "fatura_tarama_(dark)_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/fatura_tarama_(dark)_1",
    module: "scan",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "fatura_tarama_dark_2",
    folderName: "fatura_tarama_(dark)_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/fatura_tarama_(dark)_2",
    module: "scan",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "fatura_tarama_and_kayit_1",
    folderName: "fatura_tarama_&_kayıt_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/fatura_tarama_&_kayıt_1",
    module: "scan",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "fatura_tarama_and_kayit_2",
    folderName: "fatura_tarama_&_kayıt_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/fatura_tarama_&_kayıt_2",
    module: "scan",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "finansal_saglik_dark_1",
    folderName: "finansal_sağlık_(dark)_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/finansal_sağlık_(dark)_1",
    module: "analytics",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "finansal_saglik_dark_2",
    folderName: "finansal_sağlık_(dark)_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/finansal_sağlık_(dark)_2",
    module: "analytics",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "generated_screen",
    folderName: "generated_screen",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/generated_screen",
    module: "other",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: false,
  },
  {
    screenKey: "giris_dark",
    folderName: "giriş_(dark)",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/giriş_(dark)",
    module: "auth",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "giris_yap_dark",
    folderName: "giriş_yap_(dark)",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/giriş_yap_(dark)",
    module: "auth",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "giris_yap_goz_ikonlu",
    folderName: "giriş_yap_(göz_i̇konlu)",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/giriş_yap_(göz_i̇konlu)",
    module: "auth",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "giris_yap_guncellendi_1",
    folderName: "giriş_yap_(güncellendi)_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/giriş_yap_(güncellendi)_1",
    module: "auth",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "giris_yap_guncellendi_2",
    folderName: "giriş_yap_(güncellendi)_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/giriş_yap_(güncellendi)_2",
    module: "auth",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "giris_yap_renk_guncellemesi",
    folderName: "giriş_yap_(renk_güncellemesi)",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/giriş_yap_(renk_güncellemesi)",
    module: "auth",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "giris_yap_yeni_logo_1",
    folderName: "giriş_yap_(yeni_logo)_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/giriş_yap_(yeni_logo)_1",
    module: "auth",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: false,
  },
  {
    screenKey: "giris_yap_yeni_logo_2",
    folderName: "giriş_yap_(yeni_logo)_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/giriş_yap_(yeni_logo)_2",
    module: "auth",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "grup_detayi_dark_1",
    folderName: "grup_detayı_(dark)_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/grup_detayı_(dark)_1",
    module: "split",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "grup_detayi_dark_2",
    folderName: "grup_detayı_(dark)_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/grup_detayı_(dark)_2",
    module: "split",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "grup_detayi_1",
    folderName: "grup_detayı_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/grup_detayı_1",
    module: "split",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "grup_detayi_2",
    folderName: "grup_detayı_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/grup_detayı_2",
    module: "split",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: false,
  },
  {
    screenKey: "grup_harcamasi_ekle",
    folderName: "grup_harcaması_ekle",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/grup_harcaması_ekle",
    module: "split",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "grup_harcamasi_ekle_dark",
    folderName: "grup_harcaması_ekle_(dark)",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/grup_harcaması_ekle_(dark)",
    module: "split",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "guncel_islem_gecmisi_borc_kapama_dahil",
    folderName: "güncel_i̇şlem_geçmişi_(borç_kapama_dahil)",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/güncel_i̇şlem_geçmişi_(borç_kapama_dahil)",
    module: "transactions",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "guncel_makale_detayi",
    folderName: "güncel_makale_detayı",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/güncel_makale_detayı",
    module: "profile",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "guncel_yardim_makaleleri",
    folderName: "güncel_yardım_makaleleri",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/güncel_yardım_makaleleri",
    module: "profile",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "guvenlik_ve_gizlilik_ayarlari",
    folderName: "güvenlik_ve_gizlilik_ayarları",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/güvenlik_ve_gizlilik_ayarları",
    module: "profile",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "haftalik_finansal_saglik_raporu_1",
    folderName: "haftalık_finansal_sağlık_raporu_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/haftalık_finansal_sağlık_raporu_1",
    module: "analytics",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "haftalik_finansal_saglik_raporu_2",
    folderName: "haftalık_finansal_sağlık_raporu_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/haftalık_finansal_sağlık_raporu_2",
    module: "analytics",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: false,
  },
  {
    screenKey: "haftalik_rapor_koyu_mod",
    folderName: "haftalık_rapor_(koyu_mod)",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/haftalık_rapor_(koyu_mod)",
    module: "analytics",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "harcama_analizi_koyu_mod_1",
    folderName: "harcama_analizi_(koyu_mod)_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/harcama_analizi_(koyu_mod)_1",
    module: "transactions",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "harcama_analizi_koyu_mod_2",
    folderName: "harcama_analizi_(koyu_mod)_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/harcama_analizi_(koyu_mod)_2",
    module: "transactions",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "harcama_analizi_detayi_1",
    folderName: "harcama_analizi_detayı_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/harcama_analizi_detayı_1",
    module: "transactions",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: false,
  },
  {
    screenKey: "harcama_analizi_detayi_2",
    folderName: "harcama_analizi_detayı_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/harcama_analizi_detayı_2",
    module: "transactions",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: false,
  },
  {
    screenKey: "harcama_gruplari_dark_1",
    folderName: "harcama_grupları_(dark)_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/harcama_grupları_(dark)_1",
    module: "split",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "harcama_gruplari_dark_2",
    folderName: "harcama_grupları_(dark)_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/harcama_grupları_(dark)_2",
    module: "split",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "harcama_gruplari_gelismis",
    folderName: "harcama_grupları_(gelişmiş)",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/harcama_grupları_(gelişmiş)",
    module: "split",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "harcama_gruplari_1",
    folderName: "harcama_grupları_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/harcama_grupları_1",
    module: "split",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "harcama_gruplari_2",
    folderName: "harcama_grupları_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/harcama_grupları_2",
    module: "split",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "harcamayi_bol",
    folderName: "harcamayı_böl",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/harcamayı_böl",
    module: "split",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "harcamayi_bol_dark",
    folderName: "harcamayı_böl_(dark)",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/harcamayı_böl_(dark)",
    module: "split",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "hatali_giris_denemesi",
    folderName: "hatalı_giriş_denemesi",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/hatalı_giriş_denemesi",
    module: "auth",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: false,
  },
  {
    screenKey: "hesap_kilitlendi",
    folderName: "hesap_kilitlendi",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/hesap_kilitlendi",
    module: "auth",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "hos_geldiniz_onboarding_1",
    folderName: "hoş_geldiniz_(onboarding)_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/hoş_geldiniz_(onboarding)_1",
    module: "auth",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "hos_geldiniz_onboarding_2",
    folderName: "hoş_geldiniz_(onboarding)_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/hoş_geldiniz_(onboarding)_2",
    module: "auth",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "islem_detayi_dark_1",
    folderName: "i̇şlem_detayı_(dark)_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/i̇şlem_detayı_(dark)_1",
    module: "transactions",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "islem_detayi_dark_2",
    folderName: "i̇şlem_detayı_(dark)_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/i̇şlem_detayı_(dark)_2",
    module: "transactions",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: false,
  },
  {
    screenKey: "islem_detayi_1",
    folderName: "i̇şlem_detayı_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/i̇şlem_detayı_1",
    module: "transactions",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "islem_detayi_2",
    folderName: "i̇şlem_detayı_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/i̇şlem_detayı_2",
    module: "transactions",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "islem_gecmisi_dark_1",
    folderName: "i̇şlem_geçmişi_(dark)_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/i̇şlem_geçmişi_(dark)_1",
    module: "transactions",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: false,
  },
  {
    screenKey: "islem_gecmisi_dark_2",
    folderName: "i̇şlem_geçmişi_(dark)_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/i̇şlem_geçmişi_(dark)_2",
    module: "transactions",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "islem_gecmisi_dark_3",
    folderName: "i̇şlem_geçmişi_(dark)_3",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/i̇şlem_geçmişi_(dark)_3",
    module: "transactions",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "islem_gecmisi_detayi_1",
    folderName: "i̇şlem_geçmişi_detayı_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/i̇şlem_geçmişi_detayı_1",
    module: "transactions",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "islem_gecmisi_detayi_2",
    folderName: "i̇şlem_geçmişi_detayı_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/i̇şlem_geçmişi_detayı_2",
    module: "transactions",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "kapsamli_bildirim_ayarlari",
    folderName: "kapsamlı_bildirim_ayarları",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/kapsamlı_bildirim_ayarları",
    module: "profile",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "kayit_ol_dark_mode_1",
    folderName: "kayıt_ol_(dark_mode)_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/kayıt_ol_(dark_mode)_1",
    module: "auth",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "kayit_ol_dark_mode_2",
    folderName: "kayıt_ol_(dark_mode)_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/kayıt_ol_(dark_mode)_2",
    module: "auth",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "kayit_ol_goz_ikonlu",
    folderName: "kayıt_ol_(göz_i̇konlu)",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/kayıt_ol_(göz_i̇konlu)",
    module: "auth",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "kayit_ol_renk_guncellemesi",
    folderName: "kayıt_ol_(renk_güncellemesi)",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/kayıt_ol_(renk_güncellemesi)",
    module: "auth",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: false,
  },
  {
    screenKey: "kayit_ol_telefon_eklendi",
    folderName: "kayıt_ol_(telefon_eklendi)",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/kayıt_ol_(telefon_eklendi)",
    module: "auth",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "kayit_ol_yeni_logo_1",
    folderName: "kayıt_ol_(yeni_logo)_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/kayıt_ol_(yeni_logo)_1",
    module: "auth",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "kayit_ol_yeni_logo_2",
    folderName: "kayıt_ol_(yeni_logo)_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/kayıt_ol_(yeni_logo)_2",
    module: "auth",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "makale_detay_sayfasi",
    folderName: "makale_detay_sayfası",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/makale_detay_sayfası",
    module: "profile",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "makale_detayi_birikim_yontemleri",
    folderName: "makale_detayı_-_birikim_yöntemleri",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/makale_detayı_-_birikim_yöntemleri",
    module: "profile",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "nakit_odeme_onayi",
    folderName: "nakit_ödeme_onayı",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/nakit_ödeme_onayı",
    module: "transactions",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "nakit_odeme_onayi_dark",
    folderName: "nakit_ödeme_onayı_(dark)",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/nakit_ödeme_onayı_(dark)",
    module: "transactions",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "nasil_kullanilir",
    folderName: "nasıl_kullanılır?",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/nasıl_kullanılır?",
    module: "other",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: false,
  },
  {
    screenKey: "nasil_kullanilir_dark_1",
    folderName: "nasıl_kullanılır?_(dark)_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/nasıl_kullanılır?_(dark)_1",
    module: "other",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "nasil_kullanilir_dark_2",
    folderName: "nasıl_kullanılır?_(dark)_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/nasıl_kullanılır?_(dark)_2",
    module: "other",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "odeme_onayi",
    folderName: "ödeme_onayı",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/ödeme_onayı",
    module: "transactions",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "odeme_onayi_dark",
    folderName: "ödeme_onayı_(dark)",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/ödeme_onayı_(dark)",
    module: "transactions",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "profil_dark_1",
    folderName: "profil_(dark)_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/profil_(dark)_1",
    module: "profile",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "profil_dark_2",
    folderName: "profil_(dark)_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/profil_(dark)_2",
    module: "profile",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "profil_1",
    folderName: "profil_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/profil_1",
    module: "profile",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "profil_2",
    folderName: "profil_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/profil_2",
    module: "profile",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "profil_bilgilerini_duzenle",
    folderName: "profil_bilgilerini_düzenle",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/profil_bilgilerini_düzenle",
    module: "profile",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "profil_duzenle_dark",
    folderName: "profil_düzenle_(dark)",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/profil_düzenle_(dark)",
    module: "profile",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "profil_duzenle_1",
    folderName: "profil_düzenle_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/profil_düzenle_1",
    module: "profile",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "profil_duzenle_2",
    folderName: "profil_düzenle_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/profil_düzenle_2",
    module: "profile",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "sms_dogrulama_otp_1",
    folderName: "sms_doğrulama_(otp)_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/sms_doğrulama_(otp)_1",
    module: "auth",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "sms_dogrulama_otp_2",
    folderName: "sms_doğrulama_(otp)_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/sms_doğrulama_(otp)_2",
    module: "auth",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "sifremi_unuttum_dark_1",
    folderName: "şifremi_unuttum_(dark)_1",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/şifremi_unuttum_(dark)_1",
    module: "auth",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "sifremi_unuttum_dark_2",
    folderName: "şifremi_unuttum_(dark)_2",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/şifremi_unuttum_(dark)_2",
    module: "auth",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: false,
  },
  {
    screenKey: "yardim_makaleleri",
    folderName: "yardım_makaleleri",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/yardım_makaleleri",
    module: "profile",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "yardim_merkezi_yeni_kategori",
    folderName: "yardım_merkezi_-_yeni_kategori",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/yardım_merkezi_-_yeni_kategori",
    module: "profile",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "yardim_merkezi_guncellendi",
    folderName: "yardım_merkezi_güncellendi",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/yardım_merkezi_güncellendi",
    module: "profile",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "yardim_ve_destek_dark",
    folderName: "yardım_ve_destek_(dark)",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/yardım_ve_destek_(dark)",
    module: "profile",
    isDark: true,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "yardim_ve_destek_light",
    folderName: "yardım_ve_destek_(light)",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/yardım_ve_destek_(light)",
    module: "profile",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
  {
    screenKey: "yatirim_ve_tasarruf_makaleleri",
    folderName: "yatırım_ve_tasarruf_makaleleri",
    folderPath: "stitch/export/stitch_ana_ekran_dashboard/yatırım_ve_tasarruf_makaleleri",
    module: "profile",
    isDark: false,
    hasScreenPng: true,
    hasCodeHtml: true,
  },
];

export const STITCH_MODULE_COUNTS: Record<StitchModule, number> = {
  dashboard: 7,
  transactions: 18,
  analytics: 20,
  split: 17,
  scan: 4,
  profile: 30,
  auth: 24,
  other: 6,
};

export function getScreensByModule(modules: StitchModule[]): StitchScreenDefinition[] {
  const set = new Set(modules);
  return STITCH_SCREENS.filter((screen) => set.has(screen.module));
}

export function getScreenByKey(screenKey: string): StitchScreenDefinition | undefined {
  return STITCH_SCREENS.find((screen) => screen.screenKey === screenKey);
}
